### PR TITLE
WIP: update to latest hapi version

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Updating example to the latest Hapi Version

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
@geek, I updated the code.
I wait for your input and remark before updating the README accordingly. :)
(cf https://github.com/geek/hapi-example/pull/11)

**Comment by AdrieanKhisbe** [comment]
if it's ok, gonna update the README too :)

**Comment by geek** [comment]
@AdrieanKhisbe looks good

**Comment by AdrieanKhisbe** [comment]
Is there a replacement for the `hapi` executable?

cf: https://github.com/AdrieanKhisbe/hapi-plugin-example#composing-the-server

**Comment by geek** [comment]
Ya, we moved it into a separate module named `rejoice`

**Comment by AdrieanKhisbe** [comment]
Good to know! :)

**Comment by AdrieanKhisbe** [comment]
I'm trying to adapt the rejoice section, but getting the following stacktrace.

What do you see wrong in https://github.com/AdrieanKhisbe/hapi-plugin-example/commit/fa3f519b2b293bdd8c07c071f90086e138da96fc

```
module.js:340
    throw err;
    ^

Error: Cannot find module 'products'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.internals.parsePlugin (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/lib/index.js:192:23)
    at /Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/lib/index.js:102:36
    at Array.forEach (native)
    at /Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/lib/index.js:100:49
    at /Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/lib/index.js:115:9
    at iterate (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/items/lib/index.js:35:13)
```

**Comment by geek** [comment]
@AdrieanKhisbe it will try and require products.  You could npm link and npm link products or you may be able to update the plugins reference to `./` in the config

**Comment by AdrieanKhisbe** [comment]
I tried up linking, but got this error instead

```
/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/hapi/node_modules/hoek/lib/index.js:730
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Invalid plugin options {
  "options": {},
  "register" [1]: {}
}

[1] "register" must be a Function
    at Object.exports.contain.exports.reachTemplate.exports.assert (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/hapi/node_modules/hoek/lib/index.js:730:11)
    at Object.exports.apply (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/hapi/lib/schema.js:17:10)
    at module.exports.internals.Plugin.internals.Plugin.register.each [as register] (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/hapi/lib/plugin.js:221:25)
    at /Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/lib/index.js:109:20
    at iterate (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/items/lib/index.js:38:9)
    at /Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/lib/index.js:107:15
    at /Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/lib/index.js:115:9
    at iterate (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at done (/Users/abecchis/.nvm/versions/node/v5.1.0/lib/node_modules/rejoice/node_modules/glue/node_modules/items/lib/index.js:27:25)

```

**Comment by geek** [comment]
Ahh... looks like the package.json is missing a main entry

```
"main": "main.js"
```

**Pull request merged**
